/// Flutter icons EasyShopper
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EasyShopper
///      fonts:
///       - asset: fonts/EasyShopper.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EasyShopper {
  EasyShopper._();

  static const _kFontFam = 'EasyShopper';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
